spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/jxcshgl?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/


mybatis:
  typeAliasesPackage: com.springboot.springbootdemo.zyr.pojo
  mapperLocations: classpath:mapping/*.xml
server:
  port: 8080


