package com.springboot.springbootdemo.zyr.dao;

import com.springboot.springbootdemo.zyr.pojo.Customer;
import org.springframework.stereotype.Repository;

@Repository("customerDao")
public interface CustomerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_customer
     *
     * @mbggenerated
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_customer
     *
     * @mbggenerated
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_customer
     *
     * @mbggenerated
     */
    Customer selectByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table erp_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Customer record);
}